name: PHP Composer

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

permissions: write-all

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run test suite
      run: ./vendor/bin/pest tests
      
  build:

    runs-on: ubuntu-latest
    needs: test
  
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Setup Composer
      uses: php-actions/composer@v6

    - name: Vendor Permissions
      run: sudo chmod -R 777 ./vendor

    - name: Install npm dependencies
      run: npm install --omit=dev

    - name: Install composer dependencies
      run: composer install --no-dev --no-progress --no-cache -o

    - name: Build CSS
      run: npx tailwindcss -i ./src/assets/index.css -o ./public/css/style.css --minify

    - name: Rename public to www 
      run: mv ./public/ ./www/

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          ./tests
          **/tests/**
          **/.gitignore
          **/phpunit.xml
          **/start_dev.sh
          **/DOCKER_ENV
          **/docker_tag
          **/output.log

  
